@startuml
title:   磁盘I/O读写数据\n

participant 应用进程 as yy
participant 系统内核 as nh
participant DMA控制器 as dma

participant 磁盘 as cp

== I/O读数据==
autonumber

yy -> nh :read()\n系统调用\n开始阻塞
activate yy
activate nh
nh -> dma :发起I/O\n读请求
deactivate nh

activate dma
dma -> cp :发起I/O读请求
deactivate dma

activate cp
cp -> cp :读磁盘数据\n写入磁盘控\n制器缓冲区
dma <-- cp :通知数据\n读取完成
deactivate cp

activate dma
dma -> dma :从磁盘控制缓\n冲区拷贝数据\n到内核缓冲区
nh <-- dma :通知数据\n读取完成
deactivate dma

activate nh
nh -> nh :从内核缓冲区\n拷贝数据到\n用户缓冲区
yy <-- nh :read()\n调用结束\n数据返回
deactivate nh
deactivate yy


== I/O写数据==
autonumber

yy -> nh :write()\n系统调用
activate yy
yy <-- nh :ok
deactivate yy


nh -> dma :发起I/O\n写请求
activate dma
dma -> dma :从内核控制缓\n冲区拷贝数据到\n磁盘控制缓冲区
dma -> cp :发起I/O写请求
deactivate dma

activate cp
cp -> cp :将磁盘控制\n缓冲区数据\n写入磁盘
dma <-- cp : 通知数据\n写入完成
deactivate cp
activate dma
nh <-- dma : 通知数据\n写入完成
deactivate dma
@enduml
